version: "3.9"
services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - snippet_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"


volumes:
  snippet_data:
